apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
#    gitCommit: {}
    sha256: {} 
  artifacts:
  - image: nodewebapp-skf
#    sync:
#      infer:
#      - 'app/**'

deploy:
  helm:
    releases:
    - name: nodewebapp-skf
      namespace: itserious-test
      chartPath: .ci/nodewebapp
      wait: true
      valuesFiles:
      - .ci/nodewebapp/values.yaml
      values:
        image: nodewebapp-skf
      imageStrategy:
        helm: {}
      #recreatePods will pass --recreate-pods to helm upgrade
      recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #mongodburi: mongodb://
     #flags:
     #   upgrade:
     #     - --install
