apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodewebapp.fullname" . }}
  labels:
    {{- include "nodewebapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "nodewebapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
